export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const RESET_SEARCH = 'RESET_SEARCH'

export const SEARCH_STARTED = 'SEARCH_STARTED'
export const SEARCH_RESULT = 'SEARCH_RESULT'
export const MORE_SEARCH_RESULT = 'MORE_SEARCH_RESULT'
export const SEARCH_FAILED = 'SEARCH_FAILED'

export const VIEW_VIDEO_STARTED = 'VIEW_VIDEO_STARTED'
export const VIEW_VIDEO_RESULT = 'VIEW_VIDEO_RESULT'
export const VIEW_VIDEO_FAILED = 'VIEW_VIDEO_FAILED'
export const VIEW_VIDEO_UNLOAD = 'VIEW_VIDEO_UNLOAD'

// export const LIST_PLAYLIST_UNLOAD = 'LIST_PLAYLIST_UNLOAD'
// export const LIST_PLAYLIST_STARTED = 'LIST_PLAYLIST_STARTED'
// export const LIST_PLAYLIST_ITEMS = 'LIST_PLAYLIST_ITEMS'
// export const LIST_PLAYLIST_FAILED = 'LIST_PLAYLIST_FAILED'

// export const PLAYLIST_ADD_STARTED = 'PLAYLIST_ADD_STARTED'
// export const PLAYLIST_ADD_SUCCESSFUL = 'PLAYLIST_ADD_SUCCESSFUL'
// export const PLAYLIST_ADD_FAILED = 'PLAYLIST_ADD_FAILED'
